---
swagger: "2.0"
info:
  description: "An API for srv-mgmt"
  version: "0.1.0"
  title: "Srv-Mgmt Service"
  contact:
    name: "Andreas Reisenbauer"
    email: "reisenba@gmx.at"
basePath: "/api/srv-mgmt"
schemes:
- "http"
produces:
- "application/json"
paths:
  /hosts:
    get:
      tags:
      - "Hosts"
      description: >
        Get all the hosts out of our configured list and retrieve
        theirs status (up, down) plus all the properties we manage 
        as part of our application
      operationId: "getHosts"
      produces:
      - "application/json"
      responses:
        200:
          description: "host response"
          schema: 
            $ref: "#/definitions/hosts"
        400:
          description: "user-name OR role-name are not given"
          schema:
            $ref: "#/definitions/status-message"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "HostService"
  /hosts/{name}/wake:
    put:
      tags:
      - "Hosts"
      description: >
        wakes a specific host with magic packet
        there should not be an assumption this operation
        performs synchronously - it takes some time to start
        a server
        For this reason it is recommended to cyclically poll
        the server's state
      operationId: "wakeHost"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        202:
          description: "magic packet sent"
        404:
          description: "host not found"
          schema:
            $ref: "#/definitions/status-message"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "HostService"
  /version:
    get:
      tags: 
      - "Srv-Mgmt"
      description: "Returns actual API Package and Git Version"
      operationId: "statusVersion"
      responses:
        200:
          description: "returns current API Package and Git Version"
          schema:
            $ref: "#/definitions/status-message"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "SrvMgmt"
definitions:
  hosts:
    properties:
      total:
        type: "number"
        description: >
          number of entries which do meet the request
          but are skipped because of 'limit' parameter
        readOnly: true
      items:
        type: "array"
        items:
          $ref: "#/definitions/host"
  host:
    required:
    - "name"
    - "ip"
    properties:
      name:
        type: "string"
        description: "name of the host"
        readOnly: true
      ip:
        type: "string"
        description: >
          IPv4 address of the host
        pattern: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
      type:
        type: "string"
        description: "state of the booking itself"
        readOnly: true
        enum:
        - "server"
        - "client"
        - "printer"
        - "other device"
      desc:
        type: "string"
        description: "description of the host"
      wol:
        type: "boolean"
        default: false
  status-message:
    properties:
      name:
        type: "string"
        description: "package name"
      package-version:
        type: "string"
        description: "package version information"
      git-version:
        type: "string"
        description: "git version information (not guaranteed)"
